---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)

```

Column {data-width=550}
-----------------------------------------------------------------------

### Number of items ordered in every aisle by bar chart

```{r}
data('instacart')
instacart <- instacart[1:5000,]
  
instacart %>% group_by(aisle) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n)) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>%
  plot_ly(
    y = ~aisle, x = ~n, color = ~aisle,
    type = 'bar', colors = 'viridis'
  )

```

Column {data-width=450}
-----------------------------------------------------------------------

### Add-to-cart order distribution of packed products by boxplot

```{r}
instacart %>% 
  filter(aisle == c('milk')) %>% 
  mutate(product_id = as.character(product_id)) %>% 
  plot_ly(
    x= ~product_id, y = ~add_to_cart_order, color = ~product_id,
    type = 'box', colors = 'viridis'
  )

```

### Number of items ordered in every department by scatterplot

```{r}
instacart %>% 
  group_by(department_id) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n)) %>%
  mutate(text_label = str_c("Department: ", department_id)) %>% 
  plot_ly(
    x = ~department_id, y = ~n, type = "scatter", mode = "markers",
    color = ~department_id, text = ~text_label, alpha = 0.5)
```

