---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

# This is Amy's awesome website

We are going to make some plotly plots.

#Loading packages and data.

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)

```

```{r}
data('nyc_airbnb')

nyc_airbnb <- 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type,
    lat,long,rating) %>% 
  filter(borough == 'Manhattan',
         room_type == 'Entire home/apt',
         price %in% 100:500) %>% 
  drop_na(rating)

```

Let's make a scatterploy!

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c('Price:', price)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = 'scatter', mode = 'markers',
    alpha = .5, text = ~text_label
  )

nyc_airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>% 
  plot_ly(
    x = ~lat, y = ~long, type = "scatter", mode = "markers",
    color = ~price, text = ~text_label, alpha = 0.5)
```